### ISSUE TITLE
feat: 建议增加“是否自动跳转”以及“自动跳转等待时间”配置项

### ISSUE THREAD

**Issue by Barry-Flynn** [willow-god/hexo-safego#2]
增加配置项“手动/自动跳转”以及允许自行配置“自动跳转等待秒数”可以有更高的自由度，因为知乎和CSDN那种需手动点击按钮继续的中转页，感觉更能起到站外跳转提醒义务。

**Comment by willow-god** [comment]
收到啦！好想法，回头有时间了一定加上！🤩🤩🤩

**Comment by willow-god** [comment]
久等了，最新版本已经更新该功能。
