### ISSUE TITLE
包含白名单域名的链接没有替换为中间页链接

### ISSUE THREAD

**Issue by uuanqin** [willow-god/hexo-safego#4]
我发现了一个盲点🧐

白名单里添加了：
```yaml
domain_whitelist: # 域名白名单列表，包含白名单中的域名的链接将被忽略
  - 'uuanqin.top'
```

一些测试链接：
`https://www.itdog.cn`  替换为中间页链接
`https://www.itdog.cn?abcde=uuanqin.top`                         没有替换为中间页链接
`https://www.itdog.cn?asdasd=uuanqin.top&abcd=0909`   没有替换为中间页链接
`https://www.itdog.cn/ping/blog.uuanqin.top`                     没有替换为中间页链接

**Comment by willow-god** [comment]
目前不太有时间，等我考完测试一下😭😭😭

**Comment by willow-god** [comment]
欸？我感觉这个功能没有问题呀

**Comment by uuanqin** [comment]
我觉得判定链接是否应该替换为中间页链接，应该看前面的域名，不应该因为参数或路径带有白名单链接字符串就被判定为白名单链接。

比如以下链接都是跳转到www.itdog.cn网站的，应该要被替换为中间页链接才对。
https://www.itdog.cn?abcde=uuanqin.top
https://www.itdog.cn?asdasd=uuanqin.top&abcd=0909 
https://www.itdog.cn/ping/blog.uuanqin.top

**Comment by willow-god** [comment]
> 我觉得判定链接是否应该替换为中间页链接，应该看前面的域名，不应该因为参数或路径带有白名单链接字符串就被判定为白名单链接。
> 
> 比如以下链接都是跳转到www.itdog.cn网站的，应该要被替换为中间页链接才对。 [itdog.cn?abcde=uuanqin.top?abcde=uuanqin.top](https://www.itdog.cn?abcde=uuanqin.top) [itdog.cn?asdasd=uuanqin.top&abcd=0909?asdasd=uuanqin.top&abcd=0909](https://www.itdog.cn?asdasd=uuanqin.top&abcd=0909) [itdog.cn/ping/blog.uuanqin.top](https://www.itdog.cn/ping/blog.uuanqin.top)

嗷嗷嗷好的，是我的问题了，我理解错了😂我改改

**Comment by willow-god** [comment]
最新版本中应该已经处理了，友友可以更新后查看
